---
name: original pic ppt
description: Generate visually unified image-based PPT/PPTX decks from articles, Word/PDF reports, papers, notes, or outlines, strictly grounding slide content in user-provided source text when a source report is provided, and defaulting all generated decks to the 中智蓝色咨询模板风 color system unless the user explicitly requests another style. Use medium-high to high information density, top-of-page headline/storyline titles, text-rich consulting logic diagrams, and framework-style logical exposition such as house/pillar, layered architecture, process lanes, causal chains, responsibility boundaries, funnels, loops, and interpreted matrices. Avoid simple table-like grids, decorative icon-card layouts, limited blank whitespace, and bottom takeaway/callout boxes by default.
metadata:
  openclaw:
    requires:
      bins:
        - python3
    primaryEnv: OPENAI_API_KEY
    envVars:
      - name: OPENAI_API_KEY
        required: false
        description: API key for CLI fallback.
      - name: OPENAI_BASE_URL
        required: false
        description: API base URL.
      - name: CODEX_PPT_IMAGE_MODEL
        required: false
        description: Image model, defaults to gpt-image-2.
      - name: CODEX_PPT_HOME
        required: false
        description: Runtime home override.
    homepage: https://github.com/ningzimu/codex-ppt-skill
---

# Codex PPT

## Overview

This skill creates image-based PowerPoint decks from source material. Each slide is a complete 16:9 generated image. Final images are assembled into `.pptx` with `scripts/assemble_ppt.py`.

Use this when the user wants a visually unified presentation and accepts full-slide image pages. Do not use it when every textbox, chart, or shape must remain separately editable.

When the source material is a Word/PDF/text report, the deck is a synthesis of that report, not a freeform consulting rewrite. Compress, structure, and clarify the report's own content, but do not add unsupported facts, cases, data, recommendations, causes, risks, or management judgements that are not present in or directly entailed by the source text.

For source-report decks, the report's visible framework is part of the source content. Preserve explicit top-level and sub-level structure such as `一是 / 二是 / 三是`, chapter titles, paragraph order, `中央层面 / 地方层面 / 因此`, table row groups, and named subsections. Visual design may make that framework more readable, but must not replace it with a new consultant-invented framework unless the user explicitly approves the restructure.

For source-report decks, prefer the report's original wording for visible slide text. Use direct source phrases for headings, labels, judgement questions, and key points whenever they fit. Paraphrase only to shorten overlong sentences or to make a title readable, and keep the source's terms and logic labels intact. Do not replace source wording with polished but self-created consulting slogans, bottom-line claims, or summary labels. If a visible conclusion is a source sentence such as `归纳起来...`, keep it connected to the original parent structure so the reader can see which source level it summarizes.

Default style: unless the user explicitly requests another visual style, always use the bundled `中智蓝色咨询模板风` reference as the color-only style guide for decks generated by this skill. Treat this default visual style as pre-approved; do not stop to ask the user to confirm the style each time. Retain the CIIC/中智 blue, pale blue, white, charcoal, and small orange-red accent palette, but do not preserve template-specific page structures, footers, page-number blocks, city motifs, logos, bottom conclusion bands, or bottom takeaway/callout boxes unless the user explicitly asks to replicate the template layout. For consulting content pages, favor readable argument text and logic demonstration frameworks such as house/pillar structures, layered architectures, process lanes, comparison columns with convergence, interpreted matrices, causal chains, responsibility-boundary frames, funnels, loops, and compact in-body callouts. When the user asks to use framework templates or the source logic matches a bundled module, use `references/商务纯蓝框架模板库.md` and the copied assets under `assets/business-blue-framework-templates/` as structure references only. Borrow the template's structural grammar, not its visible color system: remap all fills, lines, labels, emphasis marks, and background colors to the confirmed deck palette, defaulting to `中智蓝色咨询模板风`; the original template's blue, gradients, accent allocation, and decorative color choices are not authoritative unless the user explicitly asks to reproduce them. Omit decorative icons by default; do not use icon cards, icon rows, repeated pictograms, or simple table-like grids as a substitute for analysis. Ordinary content pages should feel like management consulting pages: the body zone should show how ideas support, cause, constrain, sequence, or transform one another, not just list points in boxes.

Prefer the built-in image generation/editing tool. Use `scripts/image_gen.py` only when the built-in backend is unavailable, lacks a required capability, or the user explicitly asks for API/CLI mode.

## Hard Constraints

- Read the relevant `Reference Map` files before each phase. This file is the orchestration contract; detailed rules live in `docs/` and worker prompts in `prompts/`.
- Respect approval gates. Do not create final `deck_spec.json`, `speech.md`, prompt jobs, slide images, or `.pptx` before the approvals in `docs/workflow-gates-and-progress.md`.
- After the user approves the sample slide and authorizes full-deck generation, every remaining slide image job must be dispatched to a slide subagent whenever subagents are available.
- The main agent owns orchestration, prompt jobs, state recording, QA, speaker notes, and assembly. Do not silently replace available slide subagents with sequential production.
- Every final `origin_image/slide_XX.png` must be generated by the selected image backend: built-in image generation/editing tool or `scripts/image_gen.py`.
- Local drawing, Pillow, SVG, HTML/CSS/canvas screenshots, python-pptx/PptxGenJS layouts, and manual overlays are failure modes, not fallbacks.
- When the user provides a Word/PDF/text report as source content, every slide title/headline, key point, label, note, and recommendation must be grounded in that report. Do not invent missing facts, external cases, data, citations, conclusions, risks, or suggestions. If a useful point is only an inference, phrase it as a cautious synthesis of the report's text and keep it traceable to source sections.
- When the user provides a Word/PDF/text report as source content, visible wording should stay as close as possible to the original report. Use exact source terms, numbered labels, question stems such as `这里要回答的是`, and source conclusion phrases such as `归纳起来` when they are part of the report. Minimize self-created wording. Any necessary compression must preserve the original meaning, hierarchy, and parent-child relationship.
- When the user provides a Word/PDF/text report as source content, preserve source-framework fidelity. Before outlining, reconstruct a `source_structure_map` that records top-level sections, nested subheadings, paragraph order, and table/figure groupings. Every slide outline and prompt must inherit that map unless the user explicitly asks for a different logic framework. Do not flatten nested source logic into arbitrary peer bullets; for example, if a paragraph separates `中央层面` and `地方层面`, the slide must keep those as visible sub-level labels or as clearly nested content inside the same parent section.
- For source-report decks, each outline slide and each `deck_spec.json` slide should include `source_basis`, `source_evidence`, or equivalent local context identifying the report section, paragraph, table, figure, or user-provided asset that supports the slide. If a slide cannot be supported by the report, remove it or ask the user before adding it.
- Do not create extra visible modules that are not present in the source framework just because they look useful. If the source has three stated points, the slide may use a three-part flow, layered stack, or other visual treatment, but must not add a fourth visible module such as an independent diagnostic map, matrix, or "检审切入点" section unless that module is explicitly present in the source or the user approves the addition. Source-supported details may be shown only under their original parent section.
- For Chinese consulting/report decks, content slides must be text-rich and logic-led: use labelled diagram boxes, matrices, process arrows, responsibility-boundary frames, and summary callouts before using decorative icons. Avoid icon rows, icon-only cards, and clusters of small pictogram elements unless the user explicitly requests an icon-led visual style.
- For Chinese consulting/report decks, content slides must be framework-led rather than table-led. Before generating a slide, choose a source-grounded logic archetype such as house/pillar framework, layered architecture, process lane, causal chain, responsibility boundary, evidence-to-insight funnel, closed loop, value chain, interpreted matrix, or comparison columns with convergence. The visible layout must encode hierarchy, causality, sequence, dependency, boundary, or transformation; a plain grid of boxes is a failure unless the source itself is a table that must be preserved.
- When using the bundled business-blue framework templates, treat them as visual grammar references only: select the matching module such as 屋顶图, 多层平台, 中心发散, 循环逻辑, 业务流程, or 时间轴流程; map report content to the module's structural roles; recolor the module to the confirmed deck style, defaulting to 中智 blue / pale blue / white / charcoal with small orange-red accents; do not copy placeholder text, logos, QR codes, copyright/instruction slides, page numbers, claims, or original template color choices.
- For Chinese consulting/report decks, default to no icons on normal content pages. Use text labels, numbered markers, divider rules, arrows, matrices, tables, and callout boxes instead. If an icon is genuinely functional, use at most one small marker on a page; repeated icons beside bullet rows are a failure unless the user explicitly requests an icon-led visual style.
- For consulting/report content slides, do not allow sparse pages: normal body pages should use medium-high to high consulting information density, fill most of the usable body area, and include enough readable Chinese labels, bullets, explanatory sentences, or table/matrix cells to support the argument. As a rule of thumb, a normal content page should include 10-16 readable Chinese text units or an equivalent table/matrix, and source-rich pages should include short explanatory sentences rather than only noun labels. Large empty white areas are acceptable only for covers, section dividers, deliberate transition pages, or user-requested minimalist pages.
- For source-report decks, do not merely pour paragraphs into equal-sized boxes, generic tables, or card grids. The outline, `deck_spec.json`, and slide prompt should name the slide's `logic_archetype`, `reasoning_path`, `framework_mapping`, and a brief `why_not_table` note, unless the slide is intentionally preserving a source table/figure.
- Every normal consulting/report content slide must use the page's topmost title/headline as the storyline. The storyline is not a separate visible line and must not be rendered with the literal label `STORYLINE` or `STORYLINE：`. The top title/headline should be content-bearing and reflect the page's core topic or viewpoint, for example `华润案例：价值创造型总部与分层分类授权`.
- Do not add bottom-of-page takeaway boxes, paired bottom text boxes, bottom evidence boxes, bottom conclusion callouts, or bottom full-width conclusion slogan bands by default. If a summary viewpoint is needed, put it in the top headline or in a compact insight band between the title and the main body, then use the body to prove it.
- Summary viewpoints must be source-grounded, logically meaningful conclusions, implications, cause-effect judgements, or decision criteria. Do not add generic slogans, motivational phrases, empty catchphrases, or decorative "金句" that are not supported by the source.
- The selected image backend must stay fixed after backend confirmation. Do not let subagents switch backend for convenience.
- After sample approval, record how the approved sample was generated and pass that exact method to every slide subagent.
- When the default or confirmed style is `中智蓝色咨询模板风`, read `references/中智蓝色咨询模板风.md` as a color-only guide. Do not include template footer/page-number rules or assemble with the bundled PPTX template unless the user explicitly asks to reproduce the template layout.
- Slide dispatch and result state must be recorded with the bundled scripts. Chat messages alone do not make a slide dispatched or complete.
- If a required subagent, image backend, or required-image path is unavailable, stop and report a blocker with the slide id and evidence. Do not create a lower-quality replacement.

## Visible Progress

For non-trivial decks, keep a user-visible checklist with one active step. Canonical completion evidence is in `docs/workflow-gates-and-progress.md`.

Default visible steps:

1. Prepare source, outline, style, and backend decisions.
2. Generate and approve one sample slide.
3. Prepare slide jobs and slide state.
4. Dispatch slide subagents.
5. Record generated slide results.
6. QA, repair, notes, and PPT assembly.

Do not mark a step complete from chat alone; use real files or script-recorded state.

## Default Workflow

1. Understand the source content.
   - Identify topic, audience, goal, page count, style/brand constraints, and sections to include or exclude.
   - If the source is a Word/PDF/text report, extract and read the report text before planning. Preserve section headings, tables/figures, named entities, numbers, definitions, stated conclusions, and explicit recommendations as the source of truth.
   - If the source is a Word/PDF/text report, create a source framework inventory before any slide outline: record the original heading tree, numbered points, nested labels, paragraph sequence, and table/figure groupings. Treat this framework inventory as binding. The outline may compress wording, but it should preserve the source's parent-child relationships and order unless the user explicitly approves a reorganization.
   - Do not use general knowledge, industry assumptions, or plausible consulting patterns to fill content gaps unless the user explicitly asks for external enrichment. If the report is too thin for the requested slide count, propose fewer slides or ask for permission to add external analysis.
   - If no page count is specified, choose a practical count. Typical decks are 8-12 slides.

2. Plan the deck outline.
   - Before writing or updating `outline.md`, read `docs/workflow-gates-and-progress.md` and `docs/outline-style-and-sample.md`.
   - Draft slide roles and required source images. Ask for confirmation, then stop before style, backend, sample, or downstream artifacts until approved.
   - For consulting/report decks, map each content slide to a logic structure before visual production: house/pillar framework, layered architecture, process lane, causal chain, responsibility boundary, evidence-to-insight funnel, closed loop, value chain, interpreted matrix, comparison columns with convergence, or other source-grounded framework. Make the slide title itself serve as the page storyline/headline, and define enough slide-level text units for a medium-high density body page instead of relying on decorative whitespace.
   - For text-report decks, read `references/框架演绎版式规则.md` before finalizing the outline. Each normal content slide should include `logic_archetype`, `reasoning_path`, `framework_mapping`, and `why_not_table`. Use simple tables only when the source contains true tabular evidence or when a table best preserves exact data.
   - If the user mentions the attached framework templates, 商务纯蓝模板, 屋顶图, 多层平台, 中心发散, 循环逻辑, 业务流程, or 时间轴流程, read `references/商务纯蓝框架模板库.md` before finalizing the outline. For each slide that uses a template module, include `template_reference_module`, `template_reference_asset`, `structure_mapping`, `style_scope`, and `color_mapping`.
   - For decks based on a Word/PDF/text report, write the slide's source basis next to its title/headline and key points. The title/headline must be a faithful synthesis of source text, not a new claim. Prefer original report wording in visible slide labels and key points; record any compressed phrase only when it is a minimal shortening of a source sentence.
   - For decks based on a Word/PDF/text report, write a `Source framework` note for each slide showing the original top-level and sub-level structure being represented. The slide's visual logic structure must serve that source framework, not replace it. If a proposed visual structure would hide or scramble the original hierarchy, redesign the slide before asking for approval.

3. Apply the default visual style.
   - Before offering style options or using files from `references/`, read `docs/outline-style-and-sample.md`.
   - Use `references/中智蓝色咨询模板风.md` as the default color-only style for every deck unless the user explicitly asks for another style or asks to replicate the full template layout.
   - When using `中智蓝色咨询模板风`, restate that only the color system is retained: blue/pale-blue/white/charcoal with small orange-red accents. Body pages should be text-led, framework-led, medium-high to high density, and should not leave the main content area mostly blank; the top title/headline is the storyline and no separate storyline/core-viewpoint row should be added; omit decorative icons, avoid icon-card layouts, avoid plain table-like grids, and avoid bottom takeaway/callout boxes by default.
   - Treat the default `中智蓝色咨询模板风` as already approved and do not ask the user to confirm style selection each time. Only discuss style choices if the user explicitly asks for a different style, supplies a style reference, or asks to replicate a full template layout.

4. Confirm the image backend.
   - Before generating any slide image, read `docs/backend-selection.md`.
   - Check whether a built-in image tool is callable, state what you checked, name the backend, explain fallback status, and wait for confirmation.
   - If CLI/API fallback is selected, read `docs/cli-api-fallback.md`. Read `docs/image-model-configuration.md` only after config errors or explicit API-setting requests.

5. Generate one sample slide for approval.
   - Before generating or approving the sample slide, read `docs/outline-style-and-sample.md`.
   - Generate exactly one representative sample after outline approval, default style application, and backend confirmation. Do not generate the full deck until approved.
   - After approval, record `sample_generation_method` in `deck_spec.json` so jobs and subagents inherit the same path.

6. Create the project directory.
   - Before initializing folders or assembling files, read `docs/project-assembly-and-reporting.md`.
   - If no destination is specified, use the current working directory or the source file directory.

7. Prepare user-supplied assets.
   - Before using paper figures, charts, screenshots, logos, or other required assets, read `docs/user-supplied-assets.md`.
   - Treat required assets as strict inputs and confirm slide-to-asset mapping before generation.

8. Generate all slide images.
   - Before full-deck image generation, read `docs/slide-generation-and-subagents.md`.
   - Create per-slide jobs with `scripts/prepare_slide_prompts.py` or saved `prompts/slide_XX.json` files.
   - Every final image must come from the selected backend and be recorded with bundled state scripts.

9. Dispatch slide subagents.
   - Before dispatching or replacing slide workers, read `docs/slide-generation-and-subagents.md` and `prompts/slide-worker.md`.
   - Use one subagent per remaining slide job whenever possible. If required subagents cannot be spawned, stop and report a blocker unless the user changes the workflow.

10. Quality check and repair.
    - Before QA or assembly, read `docs/project-assembly-and-reporting.md`.
    - Inspect every slide before assembly: text, outline match, truncation, style, unwanted page numbers, overlaps, and required assets.
    - For consulting content pages, also check that the page uses readable text and a source-grounded framework as the main body, not decorative icon clusters, repeated icon cards, or a plain table/grid of boxes; the layout should reveal hierarchy, causality, sequence, dependency, boundary, or transformation. It should not leave large blank zones in the body area, should use the top title/headline as the page storyline without a separate storyline/core-viewpoint row, and should not add bottom takeaway/callout boxes or the removed bottom deep-blue conclusion band.
    - When a slide uses a bundled framework template module, also check that its colors have been remapped to the confirmed deck style. If the slide visibly keeps the template's original palette, gradients, accent allocation, or decorative color treatment instead of the 中智 color system, regenerate it with a stricter color-mapping prompt.
    - Treat normal content slides with repeated small icons, icon-led bullet rows, table-like uniform grids, independent cards with no visible reasoning path, too few Chinese text units, label-only sparse diagrams, bottom paired text boxes, bottom conclusion callouts, or slogan-like unsupported takeaways as failed samples. Regenerate them with a stricter prompt before asking the user to approve.
    - For Word/PDF/text report sources, also check that slide content is traceable to the approved outline and source basis. Regenerate or rewrite any slide that adds unsupported claims, external facts, recommendations not present in the report, or self-created summary wording that weakens or replaces the original report's terms.
    - For Word/PDF/text report sources, also check source-framework fidelity: top-level points, nested labels, and paragraph groupings from the approved outline must remain visible or clearly nested in the slide. Regenerate or rewrite any slide that arbitrarily re-groups source content, invents an extra module, erases an explicit subheading such as `中央层面 / 地方层面`, or turns nested source logic into unrelated peer bullets.
    - Regenerate severe failures with a tighter prompt. Use backend editing for localized issues when available.
    - For CLI/API fallback edit commands, read `docs/cli-api-fallback.md`. Replace the final slide only after validating the edited output.

11. Write speaker notes and assemble the PPT.
    - Before writing `speech.md` or running assembly, read `docs/project-assembly-and-reporting.md`.
    - Make sure `outline.md` reflects the final confirmed deck outline. Use `speech.md` headings that map to `Slide N`.
    - Before assembly, ensure `slide_jobs.json` shows generated slides as `recorded` and approved samples as `accepted`. If any slide is `pending`, `dispatched`, or `blocked`, stop.
    - If using `中智蓝色咨询模板风`, assemble normally without `--template` unless the user explicitly asks to preserve the original PPT template layout or master/theme metadata.

12. Report the result.
    - Use the final report checklist in `docs/project-assembly-and-reporting.md`.
    - Include paths, slide count, backend used, recorded-result status, and any limitations or blockers.

13. Save reusable styles when requested.
    - If asked to save the current deck style or a supplied image/PDF/PPT/PPTX style, read `docs/style-library.md`.

## Subagent Dispatch

Slide subagents are mandatory after sample approval whenever the runtime can spawn them. The main agent prepares jobs and records state; each worker handles exactly one `prompts/slide_XX.json` job and returns only selected image path, backend, and QA note.

Use `docs/slide-generation-and-subagents.md` for dispatch, commands, result recording, blockers, and backend provenance. Use `prompts/slide-worker.md` as the handoff template.

Subagents must not edit `outline.md`, `deck_spec.json`, other slide jobs, `origin_image/`, `speech.md`, or the final `.pptx`. The parent records outputs and assembles.

## Acceptance Criteria

- Output is a valid `.pptx`.
- Each expected final slide image exists under `origin_image/slide_XX.png`.
- Every final slide image was generated by the confirmed backend and recorded through `record_slide_result.py`, except an approved sample marked accepted by run state.
- `outline.md` reflects the approved deck outline.
- When the deck is based on a Word/PDF/text report, `outline.md`, `deck_spec.json`, prompts, and visible slide content stay grounded in the provided report. Unsupported claims, invented data, invented cases, and unrequested external recommendations are failures.
- When the deck is based on a Word/PDF/text report, `outline.md`, `deck_spec.json`, prompts, and visible slide content preserve the report's own framework and hierarchy unless the user approved a restructure. Missing explicit subheadings, arbitrary re-grouping, or extra visible modules not present in the source are failures.
- `speech.md` exists when speaker notes are expected, and assembly writes those notes into the PPT.
- Decks default to `中智蓝色咨询模板风` and visibly retain only the CIIC/中智 blue-orange color style; they do not automatically preserve the original template layouts, footers, page markers, logos, city motifs, bottom slogan bands, or original framework-template color schemes.
- Consulting/report decks are not icon-heavy or table-led: body pages use text-rich logical frameworks, house/pillar structures, layered architectures, process flows, causal chains, responsibility boundaries, funnels, loops, interpreted matrices, comparison structures, or conclusion callouts as the dominant content structure. Normal content pages omit decorative icons by default and never use repeated icon-card bullet rows unless explicitly requested.
- Consulting/report decks have visible logical演绎 value: each normal body slide shows how source points relate, support, cause, constrain, sequence, or transform one another. A slide that could be converted into a Word table without losing meaning fails unless the source table is being preserved intentionally.
- Consulting/report body pages are not sparse: normal content slides use medium-high to high management consulting information density, with most of the usable body area occupied by readable logic frames, tables, matrices, explanatory bullets, or callouts rather than empty whitespace or label-only diagrams.
- Normal consulting/report slides use a meaningful top title/headline as the page storyline. They do not render a separate storyline/core-viewpoint label or extra storyline subtitle.
- Slides do not use bottom takeaway boxes, paired bottom text boxes, bottom evidence boxes, bottom conclusion callouts, or the removed bottom orange-red block plus deep-blue white-text conclusion band unless the user explicitly asks for that layout.
- Any summary viewpoint on a slide is source-grounded and logical, and is placed in the title or near the top of the body rather than as a bottom slogan.
- `slide_jobs.json` and `slide_run_state.json` reflect the final state.
- Required source images are visibly represented, or a blocker is reported.
- If blocked, the final response identifies phase, slide id, evidence path, and unfinished reason; do not call the deck complete.

## Reference Map

- `docs/workflow-gates-and-progress.md`: approval gates, progress, completion evidence.
- `docs/backend-selection.md`: backend decision rules and confirmation text.
- `docs/outline-style-and-sample.md`: outline, style, sample rules, prompt examples.
- `docs/user-supplied-assets.md`: strict handling for required source assets.
- `docs/slide-generation-and-subagents.md`: jobs, dispatch, result recording, blockers, provenance.
- `docs/cli-api-fallback.md`: fallback runtime, generation/edit commands, image limits, troubleshooting.
- `docs/image-model-configuration.md`: API key, base URL, model, `.env`; read only when config is needed.
- `docs/project-assembly-and-reporting.md`: project directory, notes, assembly, final report, prompting principles.
- `prompts/slide-worker.md`: slide subagent handoff template.
- `references/中智蓝色咨询模板风.md`: bundled CIIC/中智咨询 color-only consulting style, prompt brief, and layout exclusions.
- `references/框架演绎版式规则.md`: source-grounded framework archetypes and anti-table rules for text-report consulting decks.
- `references/商务纯蓝框架模板库.md`: copied business-blue framework template assets, preview contact sheets, module selection rules, and template-use QA checks.
- `assets/ciic-consulting-2024-template/`: source PPTX template and rendered preview images for color extraction only; do not replicate layout unless explicitly requested.
- `assets/business-blue-framework-templates/`: copied framework PPTX templates and rendered previews for structure reference only.
- `references/*.md`: visual style references.

## Documentation and Updates

For source, docs, install, config, and examples, see [ningzimu/codex-ppt-skill](https://github.com/ningzimu/codex-ppt-skill).
